{% set version = "1.6" %}
{% set p = 'm2-' if win else '' %}
{% set n = 'm2w64-' if win else '' %}

package:
  name: htslib
  version: {{ version }}

build:
  number: 0

source:
  fn: htslib-{{ version }}.tar.bz2
  url: https://github.com/samtools/htslib/releases/download/{{ version }}/htslib-{{ version }}.tar.bz2
  md5: d6fd14e208aca7e08cbe9072233d0af9
  patches:
    - pr_571.patch
    - 0001-Skip-some-vcf-tests-on-i386.patch  # [win32]

requirements:
  host:
    - {{ n }}curl
    - {{ n }}bzip2
    - {{ n }}xz
    - {{ n }}zlib
    # Only required for libcrypto.
    # On macOS, links to libSystem
    - openssl  # [linux]
    - {{ p }}autoconf
    - {{ p }}automake          # [not win]
    - {{ p }}automake-wrapper  # [win]
    - {{ p }}pkg-config
    - {{ n }}toolchain         # [win]
    - posix                    # [win]
    # For running tests
    - {{ p }}perl

  build:
    - {{ compiler('c') }}  # [not win]
    - {{ p }}pkg-config    # [not win]
    - {{ p }}patch

  run:
    - {{ pin_compatible('curl') }}  # [not win]
    # Will be taken care of by run_exports (linux, macOS)
    # - bzip2
    # - xz
    # - zlib
    # - openssl
    - {{ n }}curl              # [win]
    - {{ n }}bzip2             # [win]
    - {{ n }}xz                # [win]
    - {{ n }}zlib              # [win]
    - {{ n }}gcc-libs          # [win]

test:
  commands:
    - bgzip --version
    - htsfile --version
    - tabix --version
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]

about:
  home: https://github.com/samtools/htslib
  license: MIT
  license_file: LICENSE
  summary: C library for high-throughput sequencing data formats.
  dev_url: https://github.com/samtools/htslib
